all_tovar_show:
   path: /
   defaults: { _controller: AcmeBazaBundle:Default:showTovar }

kategor_show:
   path: /kategor
   defaults: { _controller: AcmeBazaBundle:Default:showKategor }

tovar_show:
   path: /tovar/{idtovar}
   defaults: { _controller: AcmeBazaBundle:Default:showProduct }   